name: Sokkuri Code Reviewer
description: Linter for JavaScript projects
branding:
  icon: check-circle
  color: blue
runs:
  using: composite
  steps:
    - name: Prepare modules
      shell: bash
      run: |
        npm install --silent
        npm install --silent -g eslint-cli
    - name: ESLint
      shell: bash
      run: eslint --ext .ts, --ext .vue ./
