name: Sokkuri Code Reviewer
description: Linter for JavaScript projects
branding:
  icon: check-circle
  color: blue
runs:
  using: composite
  steps:
    - name: Log debug info
      shell: bash
      run: |
        echo NPM:
        npm -v
        echo Node:
        node -v
    - name: Prepare modules
      shell: bash
      run: |
        sudo chown -R $USER /usr/local/lib/node_modules
        sudo chown -R $USER /usr/local/bin
        npm ci
        npm install --silent -g eslint-cli
    - name: ESLint
      shell: bash
      run: eslint --ext .ts, --ext .vue ./
