name: "Sokkuri Code Reviewer"
description: "Linter docker image"

inputs:
  workspace:
    description: "Path to project"
    required: false
    default: ${{ GITHUB_WORKSPACE }}
runs:
  using: docker
  image: dockerfile
  env:
    WORKSPACE: ${{ inputs.workspace }}
