name: "Sokkuri Code Reviewer"
description: "Linter docker image"
branding:
  icon: check-circle
  color: blue
inputs:
  workspace:
    description: "Path to project"
    required: false
    default: ${{ github.workspace }}
runs:
  using: docker
  image: docker://sokkuri/code-reviewer:latest
  env:
    WORKSPACE: ${{ inputs.workspace }}
